### PR TITLE
move test templates

### PR DESCRIPTION
**Pull request by digi604**

### CODE REVIEW

**Comment by ojii** [comment]
closing because this is ancient and I don't like the idea of polluting the global Django template namespace with test templates.

**Comment by mitar** [comment]
But then testing the whole project fails? This is not good when you want to make sure everything is passing?

**Comment by ojii** [comment]
Why are you testing sekizai in your project? Do you also run the Python test suite in your project?

**Comment by mitar** [comment]
OK, I see this was fixed better in e1e6e4de0d7b2e88ad167d9b54b3dee7a57edf3b. OK. I just hope those files are available also when you install package through PyPI and not just when you git checkout.

**Comment by mitar** [comment]
> Why are you testing sekizai in your project? Do you also run the Python test suite in your project?

Because in ideal world you would never have to monkey patch anything. In reality, you do have.

**Comment by ojii** [comment]
Anyway, since 0.9.0 you should be able to run the tests after pip install.

**Comment by mitar** [comment]
Great! Thanks!

**Pull request closed without merging**
