### PR TITLE
Use tox

### PR DESCRIPTION
**Pull request by spookylukey**
This PR makes it simple for contributors to run tests on all supported versions without making a PR on GitHub, and make TravisCI use the same list.

I decided it base it off the django_19 branch - https://github.com/ojii/django-sekizai/pull/55 - to avoid re-work once that branch is merged.

### CODE REVIEW

**Comment by ojii** [comment]
Thank you for your contribution.

I really dislike tox, so unfortunately I will have to decline this pull request.

**Comment by spookylukey** [comment]
Thanks for your consideration. Is there a particular reason you dislike tox?  (I'd like to know it in case it affects the other projects where I use it). Also, do you have an alternative for people who would like to contribute, and want to run the tests on supported environments (as all good contributors would)?

**Comment by ojii** [comment]
I think using tox is a waste of disk space and time. Locally I just test "edge" configurations (lowest Py, lowest Dj, highest Py, highest Dj; so 4 configurations in total). For all the rest we have CI. Running the tests themselves is super easy, install the dependencies and execute runtests.py.

**Comment by spookylukey** [comment]
In other words, you would want to reduce the 'envlist' in tox.ini to 4 configurations. This still leaves you with the option to specify other environment. e.g. you can have:

    envlist = py26-django{13,16}, py35-django{18,19}

and doing "tox" will run 4 environments, and you are still also able to do, e.g.:

    tox -e py27-django17

That resolves that 'wasted time' argument. I'm curious how you switch between the 4 different environments that you test - it's difficult to believe it is faster for you to do that than run a single command.

I'm not sure you are serious about "wasted disk space". If you are running tests against 4 versions, you presumably have a virtualenvs for each one (or waste further time by having to manually install different Django versions). Even with all the extra configuration, the cost of each virtual environment created by tox is $0.002 with today's prices...

Personally I think that 'edge' configurations are often more numerous than you think. I've seen cases where intermediate Django versions cause problems, and intermediate Python versions can have issues too. I'd much rather find these things out sooner rather than later if developing a patch.

**Comment by ojii** [comment]
> I'm curious how you switch between the 4 different environments that you test

I have different venvs for different python versions. I generally work on one configuration and when it gets to the point I need to start testing, I switch between venvs and install the Django version I want. Thanks to wheels and pip caching, the installation is usually near-instant. Yes this isn't as fast, but it's how I do things and I like it this way.

> If you are running tests against 4 versions, you presumably have a virtualenvs for each one (or waste further time by having to manually install different Django versions).

Depending on the project, I either have only per-Python venvs (sometimes just short-lived ones) or per-Python/per-Django venvs.

> Even with all the extra configuration, the cost of each virtual environment created by tox is $0.002 with today's prices...

The "cost" for sekizai would be  almost 1GB (22*40MB). If I started using tox across my projects my home partition (which is on an "expensive", "small" SSD) would quickly run out of space, especially for projects with a lot more dependencies.


If you want to use tox, go ahead. I just don't want it in my projects (you can have a tox.ini locally in your clone).

**Comment by spookylukey** [comment]
I still don't really understand the problem. If there is a tox.ini file, you are not forced to use it, and neither is anyone else, but it makes things significantly easier for contributors who do not have your (perhaps very unusual) constraints of very limited disk space. I could indeed create a tox.ini in my own repo, but then that work has to be duplicated by everyone else who has to do the same.

I'm very happy to rewrite this patch so that:

1) the TravisCI conf is left alone
2) the envlist is reduced to 4 configurations
3) the instructions indicate how to run tests without using tox

It just seems like a no-brainer to me to help contributors run tests quickly and easily against the versions you would like patches to support.

**Pull request closed without merging**
